import pandas as pd
service=input("ENTER YOUR DEMAND - 1 , 2 , 3 , 4 , 5 : ")
if service == 1:
 print("************************")
 print("HOW YOU WANT TO VIEW DATA ? ")
 print("CHOOSE FROM BELLOW : - ")
 print("************************")
 print("1. READ ALL AS DATAFRAME")
 print("************************")
 print("2. READ WITHOUT INDEX")
 print("************************")
 print("3. READ WITHOUT HEADER")
 print("************************")
 print("4. SUMMARY OF DATAFRAME")
 print("************************")
 print("5. EXIT")
 print("************************")
 count=1
 while count <6:
  S1=input("ENTER YOUR CHOICE - 1 , 2 , 3 , 4 ,5 : ")
  count+=1
  if S1==1:
   print("5. HERE'S YOUR DATA:-")
   print("************************")
   print("************************") 
   print("************************")
   print("TITLE - WORLD LARGEST COMPANIES ON THE BASIS OF MARKET CAPITALIZATION")
   print(".....................................................................")
   print("HERE IS YOUR DATA")
   print("***********************************")
   print("***********************************")
   def data_read():
    df=pd.read_csv('D:\khushi XII\OTHERSSSSS\IP CSV WORK (ALL)\IP.csv')
    print(df)
   data_read()     
   print("***********************************")
   print("***********************************")
   print("ABBREVIATIONS USED IN COLUMNS ARE : -")
   print("............................")
   print(" AR - ANNUAL REVENUE ")
   print(" CVIM - CAPITALIZED VALUE IN MARKET ")
   print("***********************************")
   print("***********************************")
   print("ABBREVIATIONS USED IN (SECTOR) COLUMN :-")
   print("............................")
   print("1) CONSUMER DISCRETIONARY : CD")
   print("............................")
   print("2) CONSUMER STAPLES : CS")
   print("............................")
   print("3) HEALTH CARE : HC")
   print("............................")
  elif S1== 2:
   print("HERE IS YOUR DATA")
   print("***********************************")
   print("***********************************")
   def data_selectedcols():
    df=pd.read_csv('D:\khushi XII\OTHERSSSSS\IP CSV WORK (ALL)\IP.csv',index_col=0)
    print(df)
   data_selectedcols()
   print("............................")
  elif S1==3:
   print("HERE IS YOUR DATA")
   print("***********************************")
   print("***********************************")
   def data_withoutheader():
    df=pd.read_csv('D:\khushi XII\OTHERSSSSS\IP CSV WORK (ALL)\IP.csv', header=None)
    print(df)
   data_withoutheader()
  elif S1==4:
   print("HERE IS YOUR DATA")
   print("***********************************")
   print("***********************************")
   df=pd.read_csv('D:\khushi XII\OTHERSSSSS\IP CSV WORK (ALL)\IP.csv')
   df.info()  
  elif S1==5:
   print("*****************")
   print("OKAY , EXITING !!")
   print("*****************")
   count=7
  else:
         print("!!!!!!!!!!!!!!!!!!")
         print("INVALID OPTION !!")
         print("!!!!!!!!!!!!!!!!!!")
         print("*****************************************************")
         print("*****************************************************")
         print("WELCOME , HOW MAY I HELP YOU ? ")
         print("*****************************************************")
         print("FOLLOWING ARE THE SERVICES WHICH I CAN PROVIDE YOU !!")
         print("*****************************************************")
         print("CHOOSE FROM BELLOW !! ")
         print("............................")
         print("1. FETCH DATA")
         print("............................")
         print("2. ACCESS ROWS AND COLUMNS")
         print("............................")
         print("3. VIEW VISUALIZED DATA")
         print("............................")
         print("4. PERFORM AGGREGATE FUNCTIONS")
         print("............................")
         print("5. EXIT")
         print("............................")
else:
    print("invalid option")